USE ACT_DATA_201902_TEST

GO
DROP TABLE _UL_NULLvalues

GO
SELECT A.POLNO
	, a.[packcode] [packcode_orig]
	, A.[PLAN]
	, A.[PARTNER]
	, A.[BRANCHCODE]
	, A.PPSTAT
	, B3.[SPCODE]
	, B1.*
INTO _UL_NULLvalues
FROM [STRUC_UL] A -- INSERT TARGET RAW UL DATA TABLE LOCATION HERE
LEFT JOIN [UL_DIST_MODEL] B2 ON A.[PARTNER] = B2.[PARTNER]
LEFT JOIN [SPCODE] B3 ON B2.[DIST] = B3.[DIST]
LEFT JOIN [UL_MODEL] B1 ON B2.[DIST] = B1.DIST
	AND A.PACKCODE = B1.PACKCODE
	AND A.[PLAN] = B1.PRODUCT
WHERE A.PPSTAT = 'IF' AND A.[plan] NOT IN ('R7SD')

-- Construct custom procedure
DECLARE @TB NVARCHAR(512) = N'DBO.[_UL_NULLvalues]';

DECLARE @SQL NVARCHAR(MAX) = N'SELECT * FROM ' + @TB
    + ' WHERE 1 = 0';

SELECT @SQL += N' OR ' + QUOTENAME(NAME) + ' IS NULL'
    FROM SYS.COLUMNS 
    WHERE [OBJECT_ID] = OBJECT_ID(@TB);

-- Run procedure
EXEC SYS.SP_EXECUTESQL @SQL;
